language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

script:
  # Do stuff
  - touch a

install:
  # Install Codecov
  - pip install codecov

  # Install requirements
  - pip install -r requirements.txt

after_success:
  # Upload code coverage to Codecov
  - codecov
